base_dir: "./"
data_dir: "./data"
dataset_dir: "./dataset/sorted_dataset"
processed_dir: "./data/processed"
features_dir: "./data/features"
metadata_dir: "./data/metadata"
debug_dir: "./data/features/debug"