base_dir: "./"
data_dir: "./data"
dataset_dir: "./dataset/DBII"
processed_dir: "./data/processed"
features_dir: "./data/features"
metadata_dir: "./data/metadata"
log_dir: "./logs"
temp_dir: "./temp"
debug_dir: "./data/features/debug"