name: multimodal_biometric
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # --- Python version ---
  - python=3.10

  # --- PyTorch stack ---
  - pytorch=2.3.*
  - torchvision=0.18.*
  - torchaudio=2.3.*
  # (solo se usi GPU NVIDIA su Windows/Linux)
  # - pytorch-cuda=11.8

  # --- Core scientific stack ---
  - numpy<2.0
  - pandas>=2.1,<3.0
  - scikit-learn>=1.3,<2.0
  - scipy>=1.11,<2.0
  - scikit-image>=0.22,<1.0
  - pillow>=10.0,<13.0
  - pyyaml>=6.0,<7.0
  - python-dotenv>=1.0.0,<2.0.0
  - tqdm>=4.66,<5.0

  # --- Visualization ---
  - matplotlib>=3.8,<4.0
  - seaborn>=0.13,<1.0

  # --- Computer Vision / Image ---
  - opencv>=4.8,<5.0

  # --- Transformers / Vision models ---
  - timm>=0.9.2,<1.0
  - transformers>=4.41.2,<5.0
  - einops>=0.7.0,<1.0
  - albumentations>=1.4.3,<2.0

  # --- Logging / Training monitor ---
  - tensorboard>=2.15,<3.0

  # --- Web / API / Utils ---
  - pip

  - pip:
      - grad-cam>=1.5.0,<2.0
      - flask>=3.0.0,<4.0
      - fastapi>=0.110.0,<1.0
      - uvicorn>=0.29.0,<1.0
      - pillow-avif-plugin==1.4.1
      - psycopg2-binary
      - hdbscan
      - umap-learn
